source 'https://github.com/CocoaPods/Specs.git'
install! 'cocoapods', :deterministic_uuids => false
inhibit_all_warnings!

target 'Double-4K' do
  platform :ios, '12.4'
  pod 'MobileVLCKit', '~>3.3.0'
end
