stages:
    - build

variables:
    VLC_VERSION: "4.0"
    VLC_PATH: /Users/videolanci/sandbox/bin

############
## Builds ##
############

.continous-job-base-main:
    tags:
        - macos-xcode26
    stage: build
    only:
        - merge_requests
    interruptible: true

.continous-build-base-main:
    script:
        - ./compileAndBuildVLCKit.sh -${BUILD_PARAM}
    after_script:
        - rm -rf build/ || true
        - rm -rf libvlc/vlc || true
        - rm -rf *-binary || true

continous-VLCKit-iOS-main:
    extends:
        - .continous-job-base-main
        - .continous-build-base-main
    variables:
        BUILD_PARAM: "vf"
        JOB_NAME: "MobileVLCKit"

continous-VLCKit-tvOS-main:
    extends:
        - .continous-job-base-main
        - .continous-build-base-main
    variables:
        BUILD_PARAM: "vft"
        JOB_NAME: "TVVLCKit"

continous-VLCKit-macOS-main:
    extends:
        - .continous-job-base-main
        - .continous-build-base-main
    variables:
        BUILD_PARAM: "vx"
        JOB_NAME: "VLCKit"

continous-VLCKit-xrOS-main:
    extends:
        - .continous-job-base-main
        - .continous-build-base-main
    variables:
        BUILD_PARAM: "vfi"
        JOB_NAME: "VLCKit-watchOS"

continous-VLCKit-watchOS-main:
    extends:
        - .continous-job-base-main
        - .continous-build-base-main
    variables:
        BUILD_PARAM: "vfw"
        JOB_NAME: "VLCKit-watchOS"

############################################################
## Dev artifacts & release builds                         ##
## Compile all 5 platforms, then create a single package  ##
############################################################

dev-artifacts-VLCKit:
    tags:
        - macos-xcode26
    stage: build
    rules:
        - if: '$CI_PIPELINE_SOURCE == "push" && $CI_PROJECT_PATH == "videolan/VLCKit"'
        - if: '$CI_COMMIT_TAG'
    artifacts:
        paths:
            - ./*.tar.xz
    script:
        - ./compileAndBuildVLCKit.sh -f
        - rm -rf libvlc/vlc || true
        - ./compileAndBuildVLCKit.sh -ft
        - rm -rf libvlc/vlc || true
        - ./compileAndBuildVLCKit.sh -xf
        - rm -rf libvlc/vlc || true
        - ./compileAndBuildVLCKit.sh -fi
        - rm -rf libvlc/vlc || true
        - ./compileAndBuildVLCKit.sh -fw
        - ./Packaging/create-distributable-package.sh -a -x -m -t -i -w
        - mv *.tar.xz VLCKit-${VLC_VERSION}-`date +%Y%m%d-%H%M`.tar.xz
        - rm -rf build/ || true
        - rm -rf libvlc/vlc || true
    after_script:
        - rm -rf build/ || true
        - rm -rf libvlc/vlc || true
        - rm -rf *-binary || true
